"""
Intelligence package for THERMOSCOPE-AI.
Includes weak supervision labeling functions, rules, ML models, and hybrid consensus engines.
"""
from app.intelligence.labeling_functions import (
    ABSTAIN,
    INDUSTRIAL_FIRE,
    GAS_FLARE,
    MINING_ACTIVITY,
    AGRICULTURAL_BURN,
    FOREST_NATURAL_FIRE,
    INDUSTRIAL_PROCESS_HEAT,
    UNCLASSIFIED,
    ALL_LABELING_FUNCTIONS,
    LABELING_FUNCTION_MAP,
    apply_labeling_functions,
    aggregate_votes,
    compute_vote_summary,
    get_feature,
    get_numeric_feature,
    get_distance_meters,
    get_frp,
    get_brightness,
    get_confidence,
    is_night,
    get_firms_type,
    is_missing,
)

__all__ = [
    "ABSTAIN",
    "INDUSTRIAL_FIRE",
    "GAS_FLARE",
    "MINING_ACTIVITY",
    "AGRICULTURAL_BURN",
    "FOREST_NATURAL_FIRE",
    "INDUSTRIAL_PROCESS_HEAT",
    "UNCLASSIFIED",
    "ALL_LABELING_FUNCTIONS",
    "LABELING_FUNCTION_MAP",
    "apply_labeling_functions",
    "aggregate_votes",
    "compute_vote_summary",
    "get_feature",
    "get_numeric_feature",
    "get_distance_meters",
    "get_frp",
    "get_brightness",
    "get_confidence",
    "is_night",
    "get_firms_type",
    "is_missing",
]
