"""
check_data_integrity.py
Pre-training data integrity guard for THERMOSCOPE-AI.

Run this before any training run:
    python scripts/check_data_integrity.py

Fails with exit code 1 if:
  (a) classified_hotspots_v2.csv contains the _is_synthetic_demo marker column
      (generated by build_demo_dataset.py — NEVER for training).
  (b) Any occurrence of allow_demo_fallback=True is found in the training
      code path (hotspot_service.py, dataset_builder.py, train.py, evaluate.py,
      build_real_dataset.py).
"""
from __future__ import annotations

import os
import sys
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def check_no_synthetic_marker(csv_path: Path) -> bool:
    """
    GUARD A: Reject any classified_hotspots_v2.csv that has _is_synthetic_demo column.
    """
    print(f"[Guard A] Checking {csv_path} for synthetic demo marker...")
    if not csv_path.exists():
        print(f"  WARNING: CSV not found at {csv_path}. Run build_real_dataset.py first.")
        return False  # Counts as a failure — must exist before training

    # Read just the header line to check column names (fast)
    with open(csv_path, "r", encoding="utf-8") as f:
        header = f.readline().strip()

    columns = [c.strip() for c in header.split(",")]
    if "_is_synthetic_demo" in columns:
        print("  FAIL: '_is_synthetic_demo' column found!")
        print("  This CSV was generated by build_demo_dataset.py.")
        print("  It is SYNTHETIC and must NEVER be used for training.")
        print("  Fix: python scripts/build_real_dataset.py")
        return False

    print(f"  OK: No synthetic marker. {len(columns)} columns found.")
    return True


def check_no_demo_fallback_in_training_code() -> bool:
    """
    GUARD B: Ensure allow_demo_fallback=True is never called from training code paths.
    """
    TRAINING_FILES = [
        ROOT / "backend" / "app" / "services" / "hotspot_service.py",
        ROOT / "backend" / "app" / "ml" / "dataset_builder.py",
        ROOT / "backend" / "app" / "ml" / "train.py",
        ROOT / "backend" / "app" / "ml" / "evaluate.py",
        ROOT / "scripts" / "build_real_dataset.py",
    ]
    # Pattern matches allow_demo_fallback=True (with optional spaces)
    pattern = re.compile(r"allow_demo_fallback\s*=\s*True")

    print("[Guard B] Checking training code paths for allow_demo_fallback=True...")
    violations = []
    for fpath in TRAINING_FILES:
        if not fpath.exists():
            continue
        text = fpath.read_text(encoding="utf-8")
        matches = [(i + 1, line.strip()) for i, line in enumerate(text.splitlines())
                   if pattern.search(line)]
        if matches:
            for lineno, line in matches:
                violations.append((fpath.relative_to(ROOT), lineno, line))

    if violations:
        print("  FAIL: allow_demo_fallback=True found in training code:")
        for fpath, lineno, line in violations:
            print(f"    {fpath}:{lineno}: {line}")
        print("  Training code must NEVER call OSM service with demo fallback enabled.")
        return False

    print(f"  OK: No allow_demo_fallback=True in {len(TRAINING_FILES)} training files.")
    return True


def main() -> int:
    print("=" * 65)
    print("THERMOSCOPE-AI: Data Integrity Pre-Training Guard")
    print("=" * 65)

    csv_path = ROOT / "data" / "classified" / "classified_hotspots_v2.csv"

    results = [
        check_no_synthetic_marker(csv_path),
        check_no_demo_fallback_in_training_code(),
    ]

    print("=" * 65)
    if all(results):
        print("ALL GUARDS PASSED. Safe to run training.")
        return 0
    else:
        failed = sum(1 for r in results if not r)
        print(f"FAILED {failed}/{len(results)} integrity guard(s). DO NOT RUN TRAINING.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
